name: deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Executa os comandos no servidor
    runs-on: self-hosted
    steps:
      - run: |
          cd /home/ubuntu/www/pizzaiolo
          git reset --hard HEAD
          git pull origin main
          yarn
          yarn prisma:generate
          yarn prisma:push
          yarn build
          pm2 restart pizzaiolo --update-env
          pm2 restart prismaiolo --update-env
